### ISSUE TITLE
Source code request

### ISSUE THREAD

**Issue by 1049451037** [JD-AI-Research-Silicon-Valley/SACN#1]
Hi, I am very interested in your research! May I ask when the source code will be public?

**Comment by chaoshangcs** [comment]
Hi, we have uploaded the source code to GitHub. : )

**Comment by 1049451037** [comment]
Thank you very much!

**Comment by chaoshangcs** [comment]
Hi Qingsong,

Thanks for your asking. We are updating the code this week. Will publish
the newest version soon. Thanks!

Best,
Chao
