### ISSUE TITLE
A question about the WGCN in your paper

### ISSUE THREAD

**Issue by jianyucai** [JD-AI-Research-Silicon-Valley/SACN#11]
Hi,
thanks for your code, I have a question about the WGCN in your paper.

The WGCN implemented in your code seems different from the traditional GCN. Traditional GCN uses the Symmetric normalized Laplacian Matrix, but in your code, the matrix is simplified. I guess the reason might be that the weights in the adjacency matrix are trainable, so it doesn't matter whether we initialize them with the Laplacian Matrix?

I will be grateful if you could reply to this issue.

**Comment by chaoshangcs** [comment]
Hi, 
Yes, your understanding is right. In this code, we use the edge types to assign the weights to the trainable adjacency matrix.
