### ISSUE TITLE
Fix This Please

### ISSUE THREAD

**Issue by saeedizade** [JD-AI-Research-Silicon-Valley/SACN#18]
file : SACN/main.py line 209 and 210 : 
from : 
`
ranking_and_hits(model, test_rank_batcher, vocab, 'test_evaluation')  <br>
 ranking_and_hits(model, dev_rank_batcher, vocab, 'dev_evaluation')
`
change it to : 
`
ranking_and_hits(model, test_rank_batcher, vocab, 'test_evaluation',X, adjacencies) <br>
ranking_and_hits(model, dev_rank_batcher, vocab, 'dev_evaluation',X, adjacencies)
`

and this line is annoing : 
line 135 : 
`
                 print("batch number:", i)
`
change it to : 
`
if i % 10 == 0 :
            print("batch number:", i)
`

and i have no idea how to change batch size and .. because The SACN cant fit into Google Colab (SACN need 14GB ram and Colab gives us 12.7)

**Comment by chaoshangcs** [comment]
Hi, thanks for your suggestions. I have modified the code as your suggested. In addition, you can modify the hyperparameters in "https://github.com/JD-AI-Research-Silicon-Valley/SACN/blob/master/src/spodernet/spodernet/utils/global_config.py".
