### ISSUE TITLE
Code much slower than statement in paper

### ISSUE THREAD

**Issue by qiweizhen** [JD-AI-Research-Silicon-Valley/SACN#3]
In the paper, there wrote that, 'On NVIDIA Tesla P40 GPU, for FB15k-237, computation time for SACN for each epoch is about 1 minute', but in default setting of your code and with a Tesla P100 GPU, it ran about 20 minutes 1 epoch.  Did I set something wrong about your code? How many epoches would it take to converge?

**Comment by qiweizhen** [comment]
I analyzed the code with cProfile and it told me that, the GCN layer forward function took 99.6% time of the whole model forward time, and in GCN layer, tolist() function took more than half of the own time. And mul function and add_ function ranked the 2nd and 3rd most time cosuming functions.

**Comment by chaoshangcs** [comment]
Hi Qiwei, thank you so much for your messages and interests. We found a bug in the code which influences the running time. I am testing the new code now. Will upload it ASAP. Thanks!

**Comment by qiweizhen** [comment]
Thank you so much for your kindly reply

**Comment by chaoshangcs** [comment]
Dear Qiwei, I have updated a new version for testing. If you find any problem, please feel free and email me. Thanks!
