### ISSUE TITLE
Are there some parameters not included?

### ISSUE THREAD

**Issue by zanghyu** [JD-AI-Research-Silicon-Valley/SACN#4]
It seems that when I run the model using 
`CUDA_VISIBLE_DEVICES=0 python main.py model SACN dataset FB15k-237 process True`
, and I got an error 
```
Traceback (most recent call last):
  File "main.py", line 249, in <module>
    main()
  File "main.py", line 169, in main
    model = SACN(vocab['e1'].num_token, vocab['rel'].num_token)
  File "my_path/models.py", line 243, in __init__
    self.hidden_drop = torch.nn.Dropout(Config.dropout_rate)
AttributeError: type object 'Config' has no attribute 'dropout_rate'
```
And I looked in the file *src.spodernet.spodernet.utils.global_config.py*, but there is not a parameter named 'dropout_rate' and I can't find some other parameters such as 'init_emb_size' and 'channels'  either. 

Do I miss something?

**Comment by chaoshangcs** [comment]
Thanks for your message. We have updated the code. Please try it again. If you have more problems, please feel free and email me. Thanks!
