### ISSUE TITLE
Is there any result about using GCN as encoder?

### ISSUE THREAD

**Issue by 1049451037** [JD-AI-Research-Silicon-Valley/SACN#6]
I think the result is necessary to prove that SACN not only works, but also works better than the un-structure-aware GCN.

**Comment by chaoshangcs** [comment]
Hi, thank you so much for your advise. The basic idea for our paper is the "X-GCN + ConvTransE". Here the "X-GCN" could be traditional GCN, weighted GCN, graph attention network or others. In our code, we only provide the weight GCN. I believe it's worth trying using other ways. If you wanna to use the traditional GCN, I can provide one way as following:
1. In "main.py", when you create the sparse matrix between row 130 and row 152, you can replace row 148 by: 
data = data + [1 for i in range(num_entities)]
2. Replace the forward function in class GraphConvolution by:
        A = torch.sparse_coo_tensor(adj[0], adj[1], torch.Size([adj[2],adj[2]]), requires_grad = True)
        A = A + A.transpose(0, 1)
        support = torch.mm(input, self.weight)
        output = torch.sparse.mm(A, support)
...

Thanks for your message! If you have any question, please feel free and email me. Thanks!

**Comment by 1049451037** [comment]
@chaoshangcs Thank you for your reply!
